### PR TITLE
Derive commands

### PR DESCRIPTION
**Pull request by BrianHicks**
This uses clap's derive macros to get way more type-safety in the app!

⚠️ please don't merge before https://github.com/NoRedInk/firstaide/pull/6

### CODE REVIEW

**Review by jali-clarke — COMMENTED** [review]
tested in the monorepo by updating the niv ref: `niv update firstaide -b derive-commands` (locked at ref a0a9438b714532d9cdf99e027647bb94a3f9a2a7)

doing `./bootstrap` post-update results in the following error:

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /private/tmp/nix-build-firstaide-0.1.6.drv-0/firstaide-0.1.6-vendor.tar.gz/clap_derive/src/lib.rs:16:10
   |
16 | #![doc = include_str!("../README.md")]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
```

this could rightly be considered a problem out of scope of this PR since that might be a nix thing, didn't dig in any further than that

that aside, it looks good but it's not clear as to where some of the help strings went, e.g. https://github.com/NoRedInk/firstaide/pull/7/files#diff-7e862dfc3498ff86346ec84e02b3ccf6d7fa5e5d21f7c492ba7b536b915b0396L26-L28

**Comment by BrianHicks** [comment]
I'll have a look at that problem soon!

As for the help strings, they get sourced from doc comments like so: https://github.com/NoRedInk/firstaide/pull/7/files#diff-7e862dfc3498ff86346ec84e02b3ccf6d7fa5e5d21f7c492ba7b536b915b0396R21-R24

**Comment by jali-clarke** [comment]
> As for the help strings, they get sourced from doc comments

truly magical, that.  as for the nix thing, i think that's out of scope of this PR; will approve

**Review by jali-clarke — APPROVED** [review]

**Comment by BrianHicks** [comment]
I looked into the error you saw a little more and it looks like it's because we're using an older version of `rustc` in the monorepo. I'll have to update that soon.

**Pull request merged**
